### ISSUE TITLE
Hot module reloading for cshtml files

### ISSUE THREAD

**Issue by rabberbock** [Sebazzz/SystemWebpack#1]
Hello. 

Can't wait to give this a try!

Does this support HMR with cshtml files, or just with javascript and css files? Also if by any chance you have a sample app, I would love to see it.

Thanks,

Raffi

**Comment by Sebazzz** [comment]
You can find a sample app here: 
https://github.com/Sebazzz/SystemWebpack/tree/master/src/SystemWebpackTestApp

As for the cshtml file, can you clarify what you mean? If you feed a cshtml file to webpack, for instance for use in the html-webpack-plugin, it should work fine.

**Comment by rabberbock** [comment]
Thanks for the tip. Have you experienced slowness in the initial load of the website due to the HMR? My application seems to start up a bit slower.

Thanks!

**Comment by Sebazzz** [comment]
Well, it is not only due to HMR but due to the webpack dev middleware itself. ASP.NET Core has this issue as well. This is because when a static file, like probably your CSS or javascript, is requested, webpack is invoked first.

The middleware can't know your files are already up to date. If anything, this is a problem what webpack itself should solve: not compile when up to date.
