### ISSUE TITLE
Leaking Node processes on app restart

### ISSUE THREAD

**Issue by brettmason-bpac** [Sebazzz/SystemWebpack#3]
When the application is restarted any existing node/webpack processes are not getting cleaned up. This results in many copies of Node running all running webpack.

**Steps to reproduce:**
1. Setup SystemWebPack as per the Reademe.md.
2. Startup your application without the debugger.
3. Observe there is a single child node process under IIS in Sysinternals Process Monitor.
4. Make a change to your web.config to trigger the application to restart.
5. Observe there are now two child node processes under IIS. Each time IIS is restarted
6. 

**Expected behaviour:**
Only a single copy of Node/Webpack is running after the application restarts.

**Observed behaviour:**
Only a single Node/Webpack is running. Also happens if you make a server side code change and re-launch the application so the number of Node processes can build up fairly quickly.

Example after 6 app restarts.
![image](https://user-images.githubusercontent.com/15371060/59306281-0971bf80-8cf0-11e9-8081-8238bb4ff495.png)

Workaround:
Add code to SystemWebpackConfiguration.cs to kill any child Node processes at application startup.

**Comment by Sebazzz** [comment]
We are [killing node processes on exit](https://github.com/Sebazzz/SystemWebpack/blob/0152f9b8cc7c31d873b2d9fbf14fb2ea0010abd8/src/SystemWebpack/Core/NodeServices/HostingModels/OutOfProcessNodeInstance.cs#L278). Apparently it doesn't work in some cases.

**Comment by Thaurin** [comment]
Is this being looked at? So far, this has been running pretty well, but this is still an issue.

**Comment by Sebazzz** [comment]
No, I haven't had the time yet.

I suspect it has something to do with the way the node process is killed. We should probably send a Ctrl-C.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Thaurin <notifications@github.com>
Verzonden: Friday, March 6, 2020 4:15:47 PM
Aan: Sebazzz/SystemWebpack <SystemWebpack@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [Sebazzz/SystemWebpack] Leaking Node processes on app restart (#3)


Is this being looked at? So far, this has been running pretty well, but this is still an issue.

**Comment by Thaurin** [comment]
Fair enough. I've only started using this yesterday and so far I'm happy enough to be able to hot-replace in a Web Forms project at all! So I'm absolutely interested in this being stable enough for production and not running into some show-stopping bug later on.

This has the potential to make my life with legacy Web Forms projects manageable!

**Comment by Sebazzz** [comment]
I appreciate your comment. With small projects like this it is hard to gather info if it is actually used.

The problem with running webpack as part of the webserver process is that is increased the write/compile/debug cycle because every time the application pool or IIS (express) restarts, webpack also restarts.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Thaurin <notifications@github.com>
Verzonden: Friday, March 6, 2020 4:24:32 PM
Aan: Sebazzz/SystemWebpack <SystemWebpack@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [Sebazzz/SystemWebpack] Leaking Node processes on app restart (#3)


Fair enough. I've only started using this yesterday and so far I'm happy enough to be able to hot-replace in a Web Forms project at all! So I'm absolutely interested in this being stable enough for production and not running into some show-stopping bug later on.

This has the potential to make my life with legacy Web Forms projects manageable!

**Comment by Thaurin** [comment]
Yeah, I’m still evaluating whether this will really help me. I’m currently adding more front-end to a mostly backend-only ancient Web Forms application using Vue, but if using webpack during development on a Web Forms application turns out to be too much of a hassle, I might go back to a workflow without a build step.

I'd be missing out of a couple of very nice features, of course, but at least it'd work reliably. However, I would also like to break free of these Web Forms shackles and enter the age of modern front-end development.

In any case, great work on this project. How have your own experiences with it been?

**Comment by Sebazzz** [comment]
Fixed in `v1.0.0-beta3`

> In any case, great work on this project. How have your own experiences with it been?
What I stated are my primary concerns, once the project grows the compile times increase. An alternative is using either the [Webpack task runner](https://marketplace.visualstudio.com/items?itemName=MiguelAlho.YarnTaskRunner) or if you configure yarn for webpack, the [yarn task runner](https://marketplace.visualstudio.com/items?itemName=MiguelAlho.YarnTaskRunner) in Visual Studio. 

The advantage of this library though, is that is is almost ready to go. Restore the yarn packages and go.

**Comment by Thaurin** [comment]
> Fixed in `v1.0.0-beta3`

Hey, nice work!

> What I stated are my primary concerns, once the project grows the compile times increase. An alternative is using either the Webpack task runner or if you configure yarn for webpack, the yarn task runner in Visual Studio.
> The advantage of this library though, is that is is almost ready to go. Restore the yarn packages and go.

Yeah, I noticed some increase in compile time, but I still need to optimize my webpack configuration. This is actually the frist time I'm doing any front-end work of significance, so it is still all fairly new to me. Thanks for pointing out webpack task runner. Is it also capable of hot module replacement in `System.Web` projects?

I'll check this update out next week! Thanks for fixing the issue.

**Comment by Sebazzz** [comment]
You're welcome!

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Thaurin <notifications@github.com>
Verzonden: Saturday, March 7, 2020 10:20:04 PM
Aan: Sebazzz/SystemWebpack <SystemWebpack@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [Sebazzz/SystemWebpack] Leaking Node processes on app restart (#3)


Fixed in v1.0.0-beta3

Hey, nice work!

What I stated are my primary concerns, once the project grows the compile times increase. An alternative is using either the Webpack task runner or if you configure yarn for webpack, the yarn task runner in Visual Studio.
The advantage of this library though, is that is is almost ready to go. Restore the yarn packages and go.

Yeah, I noticed the increase in compile time, but I still have to optimize my webpack configuration. This is actually the frist time I'm doing any front-end work of significance, so it is still all fairly new to me.

I'll check this out more next week! Thanks for fixing this issue.
