### ISSUE TITLE
Strong name signing

### ISSUE THREAD

**Issue by thelok** [Sebazzz/SystemWebpack#5]
I have an error loading SystemWebpack on startup and I get the following error:

`
Could not load file or assembly 'SystemWebpack, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
`

Can you publish a version on Nuget with strong name signing?

**Comment by Sebazzz** [comment]
I'd rather not because that would be:
1. A breaking change
2. Strong-naming is not really necessary for web applications (which are the consumers of this library). If you managed to slip a fake assembly in an web application, then you're already on the other side of the watertight hatch. Nothing would stop an attacked from completely taking over the website. For verification even Microsoft doesn't recommend strong naming anymore, but Authenticode instead, if I recall correctly. 

I hope you understand my reasoning. I'm happy to hear your thoughts on this.

**Comment by thelok** [comment]
Alright, understood, I'll think about not signing our web application. Thanks for responding.
